version: "3"

services:
  app:
    container_name: femashr-puncher
    build: .
    restart: always
    env_file:
      - .env
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ./logs:/app/logs
